### ISSUE TITLE
Reloading PATH and NIX_GHC env variables from nix-shell

### ISSUE THREAD

**Issue by jb55** [travisbhartwell/nix-emacs#11]
Right now I have to close emacs, re-run nix-shell, and reopen emacs again to reload my NIX_GHC paths for ghc. It would be awesome if there was some function that ran nix-shell and reloaded the exec-path and environment variables without having to restart emacs.

**Comment by travisbhartwell** [comment]
I've been thinking about this actually.  I don't have time at the moment, but I'll comment later on strategies for implementing this.

**Comment by jb55** [comment]
I have some simple code snippets that reload the exec-path, I'm hoping to have something more useful soon.

**Comment by CestDiego** [comment]
Awesom! :)

**Comment by travisbhartwell** [comment]
I'm thinking we'll want to do another package (since the ones we have right now are focused on nixos options and not general-purpose).  I was just thinking about some other functions that I might find useful.  Perhaps name this `nix-utils.el` or something?

**Comment by CestDiego** [comment]
I think we should have more like nix-core.el that we also use in the nixos-options, I've been working on a nixos-packages and it also has to use most of the code of nixos-options
