### ISSUE TITLE
Utilities for operating with nix-shell environments

### ISSUE THREAD

**Issue by svenkeidel** [travisbhartwell/nix-emacs#16]
Hi,

independently from this repository, I developed a few utility functions for working with nix-shell environments [link](https://github.com/svenkeidel/emacs.d/blob/master/nixos.el). I think these functions could be beneficial for this repository and I would like to merge my work with yours.

The functions include:
* `nix-shell-command` to compose a nix-shell command string that can be passed to the commandline
* `nix-shell` that directly executes a command in the given sandbox
* `nixos-find-sandbox` searches from the given path upwards until it finds a `*.nix` file.
* `nixos-current-sandbox` searches from the current working directroy upwards until it finds a `*.nix` file
* `nixos-executable-find`, a replacement for the built-in `executable-find`. It searches in the given sandbox for executables.

Let me know what you think.

Best,
Sven

**Comment by CestDiego** [comment]
I'm +1

**Comment by travisbhartwell** [comment]
Yeah, looks good to me.  Perhaps would could add this to this repo, update the MELPA request to pull in another library, and make you a collaborator?

The only thing I see that this would need (just at first glance) is probably some autoload lines.

Looks good.  I may not have time until tomorrow to get to this, but I appreciate you sharing!
