### ISSUE TITLE
publish nix-sandbox to melpa

### ISSUE THREAD

**Issue by wedens** [travisbhartwell/nix-emacs#23]
I've been using nix-sandbox for about a month with haskell-mode and flycheck and it works fine. 
I think it's ready to be published to melpa.

/cc @svenkeidel

**Comment by svenkeidel** [comment]
Do you use #22? `nix-sandbox` in `master` has severe disk space leak, see #21. I could also need a code review for #22. It certainly works on my machine, but this doesn't mean that it breaks on others.

**Comment by wedens** [comment]
no. I use nix-sandbox from master. I haven't noticed any space leak.

**Comment by svenkeidel** [comment]
I opened a pull request on MELPA: https://github.com/melpa/melpa/pull/3594

I close this issue when it is merged.
